from selenium.webdriver.common.by import By


class BasePageLocators():
    GET_COOKIE_BUTTON = (By.ID, 'rcc-confirm-button')
    ORDER_BUTTON = (By.XPATH, ".//button[text()='Заказать']")
    YANDEX_lOGO = (By.XPATH, ".//img[@alt='Yandex']")
    APP_SCOOTER_LOGO = (By.XPATH, ".//img[@alt='Scooter']")

class QuestionsPageLocators():
    COST_QUESTION = (By.XPATH, ".//div[@id='accordion__heading-0' and @role='button']")
    COST_ANSWER = (By.XPATH, ".//div[@id='accordion__panel-0' and @role='region']")
    COUNT_QUESTION = (By.XPATH, ".//div[@id='accordion__heading-1' and @role='button']")
    COUNT_ANSWER = (By.XPATH, ".//div[@id='accordion__panel-1' and @role='region']")
    TIME_RENT_QUESTION = (By.XPATH, ".//div[@id='accordion__heading-2' and @role='button']")
    TIME_RENT_ANSWER = (By.XPATH, ".//div[@id='accordion__panel-2' and @role='region']")
    START_TODAY_QUESTION = (By.XPATH, ".//div[@id='accordion__heading-3' and @role='button']")
    START_TODAY_ANSWER = (By.XPATH, ".//div[@id='accordion__panel-3' and @role='region']")
    CHANGE_RENT_TIME_QUESTION = (By.XPATH, ".//div[@id='accordion__heading-4' and @role='button']")
    CHANGE_RENT_TIME_ANSWER = (By.XPATH, ".//div[@id='accordion__panel-4' and @role='region']")
    CHARGE_QUESTION = (By.XPATH, ".//div[@id='accordion__heading-5' and @role='button']")
    CHARGE_ANSWER = (By.XPATH, ".//div[@id='accordion__panel-5' and @role='region']")
    CANCEL_ORDER_QUESTION = (By.XPATH, ".//div[@id='accordion__heading-6' and @role='button']")
    CANCEL_ORDER_ANSWER = (By.XPATH, ".//div[@id='accordion__panel-6' and @role='region']")
    OUT_OF_MKAD_QUESTION = (By.XPATH, ".//div[@id='accordion__heading-7' and @role='button']")
    OUT_OF_MKAD_ANSWER = (By.XPATH, ".//div[@id='accordion__panel-7' and @role='region']")
    HIDDEN_ANSWERS = (By.XPATH, ".//div[@role='region' and @hidden]")
    OPENED_ANSWER_TEXT = (By.XPATH, ".//div[@role='region' and not(@hidden)]/p")
    BIG_ORDER_BUTTON = (By.XPATH, ".//button[@class='Button_Button__ra12g Button_UltraBig__UU3Lp']")

class OrderPageLocators():
    NAME_INPUT = (By.XPATH, ".//input[@placeholder='* Имя']")
    SURNAME_INPUT = (By.XPATH, ".//input[@placeholder='* Фамилия']")
    ADDRESS_INPUT = (By.XPATH, ".//input[@placeholder='* Адрес: куда привезти заказ']")
    UNDEGROUND_INPUT = (By.XPATH, ".//input[@placeholder='* Станция метро']")
    UNDEGROUND_STATION_1 = (By.XPATH, ".//div[text()='Бульвар Рокоссовского']/parent::button")
    UNDEGROUND_STATION_2 = (By.XPATH, ".//div[text()='Лубянка']/parent::button")
    PHONE_INPUT = (By.XPATH, ".//input[@placeholder='* Телефон: на него позвонит курьер']")
    NEXT_BUTTON = (By.XPATH, ".//button[text()='Далее']")
    DATE_FIELD = (By.CLASS_NAME, 'Order_MixedDatePicker__3qiay')
    DATE_INPUT = (By.XPATH, ".//input[@placeholder='* Когда привезти самокат']")
    DATE_IN_CALENDAR = (By.CLASS_NAME, "react-datepicker__day react-datepicker__day--010")
    RENT_PERIOD_INPUT = (By.CLASS_NAME, "Dropdown-control")
    RENT_PERION_DROPDOWN_2_DAYS = (By.XPATH, ".//div[@class='Dropdown-option'][2]")
    RENT_PERION_DROPDOWN_5_DAYS = (By.XPATH, ".//div[@class='Dropdown-option'][5]")
    COLOR_CHOICE_BLACK = (By.XPATH, ".//label[@for='black']")
    COLOR_CHOICE_GREY = (By.XPATH, ".//label[@for='grey']")
    COMMENT_FOR_COURIER = (By.XPATH, ".//input[@placeholder='Комментарий для курьера']")
    MAKE_ORDER_BUTTON = (By.XPATH, ".//button[@class='Button_Button__ra12g Button_Middle__1CSJM' and text()='Заказать']")
    EMPTY_PLACE = (By.CLASS_NAME, "App_App__15LM-")
    CONFIRMATION_ORDER_MODAL_WINDOW = (By.CLASS_NAME, "Order_Modal__YZ-d3")
    SAY_YES_ORDER_BUTTON = (By.XPATH, ".//button[text()='Да']")
    ORDER_IS_MAID_MODAL_WINDOW = (By.CLASS_NAME, "Order_ModalHeader__3FDaJ")
    VIEW_STATUS_BUTTON_IN_MODAL_WINDOW = (By.XPATH, ".//button[text()='Посмотреть статус']")